services:
  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      # - DJANGO_SUPERUSER_EMAIL=test@test.com
      # - DJANGO_SUPERUSER_USERNAME=rishat
      # - DJANGO_SUPERUSER_PASSWORD=rishat
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "rishat", "-U", "rishat" ]
      timeout: 5s
      interval: 5s
      retries: 5
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - backend

  web_app:
    build: ./
    ports:
     - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: backend