# Generated by Django 4.1.6 on 2023-02-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_decription_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_price_id',
            field=models.CharField(default='price_id', max_length=100),
        ),
    ]
