# Generated by Django 4.1.6 on 2023-02-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_item_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stripe_price_id',
            field=models.CharField(max_length=100),
        ),
    ]
